module.exports = {
  projects: [
    '<rootDir>/libs/shared/common',
    '<rootDir>/libs/shared/repository',
    '<rootDir>/libs/repository/redis',
    '<rootDir>/libs/shared/redis-connection',
    '<rootDir>/apps/data-api',
    '<rootDir>/apps/js-chat',
    '<rootDir>/libs/repository/http-client',
    '<rootDir>/libs/repository/ng-api-client',
    '<rootDir>/libs/conversation/gateway',
    '<rootDir>/libs/repository/core-api-client',
    '<rootDir>/libs/command/queue',
    '<rootDir>/libs/command/consumer',
    '<rootDir>/libs/conversation/queue',
    '<rootDir>/libs/conversation/consumer',
    '<rootDir>/libs/stock/common',
    '<rootDir>/apps/stock-bot-worker',
  ],
};
